apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Airbrake Exception Logger
  description: Airbrake Exception Logger Plugin for the Reekoh IoT Platform
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Logger
  price: 0
  tags:
    - logger
    - exception-logger
    - airbrake
  config:
    projectId:
      label: Project ID
      type: String
      maxLength: 1000
      required: true
      help: Please provide your Airbrake.io Project ID.
    apiKey:
      label: API KEY
      type: Password
      maxLength: 1000
      required: true
      help: Please provide your Airbrake.io API key.

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??